name: lumina_zilei
description: Aplicatie rugaciuni ortodoxe romanesti
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^21.0.0
  timezone: ^0.11.0
  http: ^1.2.2
  shared_preferences: ^2.3.3
  provider: ^6.1.2
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/calendar.json
    - assets/data/prayers.json
    - assets/data/bible_quotes.json
    - assets/data/acatiste.json
    - assets/data/rugaciuni_zilnice.json
    - assets/pictures/
